### ISSUE TITLE
Fix a typo in README

### ISSUE THREAD

**Issue by jkonecny75** [diegolnasc/kubernetes-best-practices#7]
```diff
@@ -197,7 +197,7 @@ spec:
       image: gcr.io/google-samples/hello-app:1.0
       ports:
         - containerPort: 8080
-      livenessProbe:
+      readinessProbe:
         httpGet:
           path: /ready
           port: 8080
```

**Comment by diegolnasc** [comment]
Oh, Thanks for reporting.

**Comment by jkonecny75** [comment]
You are welcome ;-) ... and thank You for sharing of great knowledge

**Comment by jkonecny75** [comment]
Now there are two typos ;-)

![image](https://user-images.githubusercontent.com/19643783/133510424-a6e4ea4e-5952-47f9-bf81-78faec1412a2.png)
![image](https://user-images.githubusercontent.com/19643783/133510528-ecd083a7-3b13-40bc-90e4-b7c8d0ff1110.png)

**Comment by diegolnasc** [comment]
Wow, revised!
